pipeline {
    environment {
        DOMAIN = "${env.DOMAIN}"
        IMAGE = "felipecwb/todo-api"
    }

    agent none

    stages {
        stage('Testes') {
            agent {
                dockerfile {
                    dir 'app/'
                    filename 'Dockerfile'
                }
            }
            
            steps {
                echo "${env.DOMAIN}"
                sh 'ls -lsa'
                sh './bin/test'
            }
        }
    }
}