pipeline {
    environment {
        DOMAIN = "${env.DOMAIN}"
        IMAGE = "felipecwb/todo-api"
    }

    agent any

    stages {
        stage('Testes') {
            agent {
                dockerfile {
                    filename 'app/Dockerfile'
                    dir 'app'
                }
            }
            
            steps {
                sh 'echo "${env.DOMAIN}"'
                sh './bin/test'
            }
        }
    }
}