pipeline {
    environment {
        dockerManagerHost = "${env.DOCKER_MANAGER_HOST}"
        DOMAIN = "${env.DOMAIN}"
        IMAGE = "felipecwb/todo-api"
        stack = "todoapp"
    }

    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    dockerImage = docker.build IMAGE + ":$BUILD_NUMBER", 'app'
                }
            }
        }

        stage('Test') {
            agent {
                dockerfile {
                    dir 'app'
                    filename 'Dockerfile'
                }
            }

            steps {
                echo 'Composer: Dev Required'
                sh '''
                    cd ${WORKDIR}
                    composer install
                '''

                echo 'Integration tests'
                sh '''
                    cd ${WORKDIR}
                    bin/test
                '''
            }
        }

        stage('Deploy Image') {
            when {
                branch 'master'
            }

            steps {
                script {
                    docker.withRegistry('', 'dockerhub') {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy on Swarm') {
            when {
                branch 'master'
            }

            agent {
                docker {
                    image 'docker:latest'
                    args '-e DOCKER_HOST=${dockerManagerHost}'
                }
            }

            steps {
                sh '''
                    export ENVIRONMENT=production
                    export DOMAIN=${DOMAIN}

                    docker stack deploy \
                        --with-registry-auth \
                        --compose-file .docker/stack.yml \
                        ${stack}
                '''
            }
        }

        stage('Clean Workspace') {
            steps{
                sh "docker image prune -af"
            }
        }
    }
}