version: "3.7"

networks:
  network:
    driver: overlay

services:
  manager:
    image: alpine/socat:latest
    command: 'tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock'
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback

  worker:
    image: alpine/socat:latest
    command: 'tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock'
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback

  worker_ci:
    image: alpine/socat:latest
    command: 'tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock'
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.ci == true
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
