version: '3.7'

volumes:
  data:
    driver: local

services:
  api:
    image: todo-api
    build:
      context: .
    ports:
      - 80:8080
    environment:
      ENVIRONMENT: development
      DATABASE_DSN: mysql:host=database;port=3306;dbname=todo
      DATABASE_USER: todo
      DATABASE_PASSWORD: 05f20a71783db1a6f0c4e75ebb1914154e901af2
    volumes:
      - .:/home/todo
    depends_on:
      - database

  database:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password"
    restart: on-failure
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: 05f20a71783db1a6f0c4e75ebb1914154e901af2
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - data:/var/lib/mysql
      - ./.docker/database-entry.sql:/docker-entrypoint-initdb.d/entry.sql:ro

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    links:
      - database:db

